// js/app-admin.js
const GEMINI_API_KEY = "AQ.Ab8RN6Iy_zgBpb57OOwzghfzsF5Cw5goZUvJD804kyBsikiHLQ";
const GEMINI_MODELS = ["gemini-2.5-flash-lite","gemini-2.0-flash-lite","gemini-2.5-flash","gemini-2.0-flash","gemini-flash-latest"];
async function callGemini(prompt){ let lastError=null; for(const model of GEMINI_MODELS){ const url=`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`; for(let a=1;a<=2;a++){ const c=new AbortController(); const to=setTimeout(()=>c.abort(),45000); try{ const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.3,topP:0.8,topK:40,maxOutputTokens:8192}})}); clearTimeout(to); if(res.ok)return{data:await res.json(),model}; const ed=await res.json().catch(()=>({})); const msg=(ed&&ed.error&&ed.error.message)?ed.error.message:('HTTP '+res.status); if(res.status===404){lastError=new Error('['+model+'] tidak tersedia.');break;} if(res.status===429||res.status===503){lastError=new Error('['+model+'] '+msg); if(a===1){await new Promise(r=>setTimeout(r,2000));continue;} break;} throw new Error('['+model+'] '+msg);}catch(err){clearTimeout(to); if(err.name==='AbortError'){lastError=new Error('['+model+'] Timeout.');continue;} if(err instanceof TypeError){lastError=new Error('['+model+'] Gagal koneksi.');continue;} throw err;}}} throw lastError||new Error("Semua model sibuk."); }

const AdminApp = {
    SESSION_KEY:'jec_admin_session', allSoal:[], studentMap:{}, sessionsSnap:null, resultsSnap:null,
    init(){ this.bindAuthEvents(); this.bindNavigation(); this.bindPills(); this.bindUserManagement(); this.bindSoalManagement(); this.bindReviewListeners(); this.bindSoalListener(); this.bindOverviewListeners(); this.restoreSession(); },
    saveSession(id){try{localStorage.setItem(this.SESSION_KEY,JSON.stringify({id,at:Date.now()}));}catch(e){}},
    clearSession(){try{localStorage.removeItem(this.SESSION_KEY);}catch(e){}},
    restoreSession: async function(){try{const raw=localStorage.getItem(this.SESSION_KEY);if(!raw)return;const s=JSON.parse(raw);if(!s||!s.id)return;const d=await db.collection('admins').doc(s.id).get();if(d.exists){this.navigateView('view-dashboard');this.switchPanel('panel-overview');}else this.clearSession();}catch(e){this.clearSession();}},
    navigateView(t){document.querySelectorAll('.view-section').forEach(v=>v.classList.add('hidden'));const el=document.getElementById(t);if(el){el.classList.remove('hidden');el.classList.add('active');}},
    switchPanel(t){document.querySelectorAll('.content-panel').forEach(p=>p.classList.add('hidden'));const el=document.getElementById(t);if(el)el.classList.remove('hidden');document.querySelectorAll('.bnav-item').forEach(i=>i.classList.toggle('active',i.dataset.target===t));if(t==='panel-users')this.loadStudents();},
    bindNavigation(){document.querySelectorAll('.bnav-item').forEach(i=>i.addEventListener('click',e=>this.switchPanel(e.currentTarget.dataset.target)));},
    bindPills(){const g=[['data-sistab','.sistab'],['data-soaltab','.soaltab'],['data-inputtab','.inputtab'],['data-reviewtab','.reviewtab']];g.forEach(([attr,cls])=>{document.querySelectorAll('['+attr+']').forEach(btn=>{btn.addEventListener('click',()=>{btn.closest('.pill-bar').querySelectorAll('.pill').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll(cls).forEach(t=>t.classList.add('hidden'));const t2=document.getElementById(btn.getAttribute(attr));if(t2)t2.classList.remove('hidden');});});});},

    bindAuthEvents(){ const f=document.getElementById('form-login-admin'); if(f)f.addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('btn-login');const id=document.getElementById('adminId').value.trim();const pin=document.getElementById('adminPin').value.trim();btn.innerHTML='Memproses...';btn.disabled=true; try{const hp=await SecurityUtil.hashPin(pin);const d=await db.collection('admins').doc(id).get(); if(id==='admin'&&pin==='123456'){if(!d.exists)await db.collection('admins').doc(id).set({nama:'Super Admin',pin_hash:hp,role:'admin'});this.saveSession(id);this.navigateView('view-dashboard');this.switchPanel('panel-overview');} else if(d.exists&&d.data().pin_hash===hp){this.saveSession(id);this.navigateView('view-dashboard');this.switchPanel('panel-overview');} else Modal.alert('Admin ID atau PIN Salah!',{type:'danger',icon:'lock'});}catch(err){Modal.alert('Gagal: '+err.message,{type:'danger'});}finally{btn.innerText='Masuk';btn.disabled=false;}});
        document.getElementById('btn-logout').addEventListener('click',async()=>{const ok=await Modal.confirm('Keluar?',{confirmLabel:'Keluar',confirmClass:'danger'});if(ok){this.clearSession();this.navigateView('view-login');}}); },

    // ============ MANAGE SISWA ============
    bindUserManagement(){
        document.getElementById('form-add-student').addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('btn-save-student');btn.disabled=true; const id=document.getElementById('add-id').value.trim(); const hp=await SecurityUtil.hashPin(document.getElementById('add-pin').value.trim());
            try{ await db.collection('students').doc(id).set({ nama:document.getElementById('add-nama').value.trim(), kelas:document.getElementById('add-kelas').value.trim(), batch:document.getElementById('add-batch').value.trim(), asal_sekolah:document.getElementById('add-asal').value.trim(), nama_panggilan:'', ttl:'', alamat:'', avatar:'', pin_hash:hp, status:'on', created_at:Date.now() }); document.getElementById('form-add-student').reset(); document.getElementById('add-pin').value='1234'; Modal.toast('Tersimpan','Siswa '+id+' ditambahkan.','success'); }
            catch(err){Modal.alert('Gagal: '+err.message,{type:'danger'});}finally{btn.disabled=false;}});
        document.getElementById('form-gen-auto').addEventListener('submit',async e=>{e.preventDefault(); const tahun=document.getElementById('gen-tahun').value.trim(); const batch=document.getElementById('gen-batch').value.trim(); const jumlah=parseInt(document.getElementById('gen-jumlah').value)||0;
            const snap=await db.collection('students').get(); let maxSeq=0; const prefix=tahun+batch; snap.forEach(d=>{ if(d.id.startsWith(prefix)){const seq=parseInt(d.id.slice(prefix.length)); if(!isNaN(seq)&&seq>maxSeq)maxSeq=seq;} });
            const first=prefix+String(maxSeq+1).padStart(2,'0'), last=prefix+String(maxSeq+jumlah).padStart(2,'0');
            const ok=await Modal.confirm(`Akan dibuat ${jumlah} siswa:\n${first} = Siswa ${maxSeq+1}\ns/d\n${last} = Siswa ${maxSeq+jumlah}\nPIN default 1234. Lanjutkan?`,{title:'Generate',icon:'group_add'}); if(!ok)return;
            const btn=document.getElementById('btn-gen-auto'); btn.disabled=true;btn.innerHTML='Memproses...';
            try{ const hp=await SecurityUtil.hashPin('1234'); const bw=db.batch(); for(let i=1;i<=jumlah;i++){ const seq=maxSeq+i; const id=prefix+String(seq).padStart(2,'0'); bw.set(db.collection('students').doc(id),{ nama:'Siswa '+seq, nama_panggilan:'', kelas:'', batch, asal_sekolah:'', ttl:'', alamat:'', avatar:'', pin_hash:hp, status:'on', created_at:Date.now() }); } await bw.commit(); Modal.toast('Berhasil',jumlah+' siswa ('+first+' s/d '+last+').','success'); }
            catch(err){Modal.alert('Gagal: '+err.message,{type:'danger'});}finally{btn.disabled=false;btn.innerHTML='<span class="material-symbols-rounded">group_add</span> Generate Sekarang';}});
        document.getElementById('batch-filter').addEventListener('change',()=>this.loadStudents());
        document.getElementById('btn-wipe-users').addEventListener('click',async()=>{const ok=await Modal.confirm('Hapus SEMUA siswa?',{confirmLabel:'Hapus',confirmClass:'danger'});if(!ok)return;const s=await db.collection('students').get();const b=db.batch();s.forEach(d=>b.delete(d.ref));await b.commit();Modal.toast('Selesai','Semua siswa dihapus.','success');});
        document.getElementById('btn-del-selected').addEventListener('click',async()=>{ const boxes=[...document.querySelectorAll('.student-check:checked')]; if(!boxes.length){Modal.alert('Centang siswa yang akan dihapus.',{type:'warning',icon:'info'});return;} const ok=await Modal.confirm('Hapus '+boxes.length+' siswa terpilih?',{confirmLabel:'Hapus',confirmClass:'danger'}); if(!ok)return; const b=db.batch(); boxes.forEach(x=>b.delete(db.collection('students').doc(x.dataset.id))); await b.commit(); Modal.toast('Selesai',boxes.length+' siswa dihapus.','success'); });
    },
    loadStudents(){ const filter=document.getElementById('batch-filter').value; const tbody=document.getElementById('student-list-body'); tbody.innerHTML='<tr><td colspan="10" class="text-center">Memuat...</td></tr>';
        db.collection('students').onSnapshot(snap=>{ const set=[...new Set(snap.docs.map(d=>d.data().batch||''))].sort(); const sel=document.getElementById('batch-filter'); const cur=sel.value; sel.innerHTML='<option value="">Semua Batch</option>'; set.forEach(k=>sel.innerHTML+=`<option value="${k}">Batch ${k}</option>`); sel.value=cur;
            tbody.innerHTML=''; let docs=snap.docs.slice(); if(filter)docs=docs.filter(d=>(d.data().batch||'')===filter);
            if(!docs.length){tbody.innerHTML='<tr><td colspan="10" class="text-center">Tidak ada siswa.</td></tr>';return;}
            docs.forEach(doc=>{ const d=doc.data(); const st=d.status||'on'; const col=st==='off'?'var(--danger)':'var(--success)';
                tbody.innerHTML+=`<tr><td><input type="checkbox" class="student-check" data-id="${doc.id}"></td><td><strong>${doc.id}</strong></td><td>${d.nama}</td><td>${d.nama_panggilan||'-'}</td><td>${d.kelas||'-'}</td><td>${d.asal_sekolah||'-'}</td><td>${d.ttl||'-'}</td><td>${d.alamat||'-'}</td><td style="color:${col};font-weight:bold;">${st==='off'?'Nonaktif':'Aktif'}</td>
                <td><button class="btn btn-primary" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.editStd('${doc.id}')">Edit</button>
                <button class="btn btn-accent" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.toggleStd('${doc.id}','${st}')">On/Off</button>
                <button class="btn btn-danger" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.delStd('${doc.id}')">Del</button></td></tr>`; }); }); },
    editStd: async function(id){ const d=(await db.collection('students').doc(id).get()).data(); if(!d)return; const nama=await Modal.prompt('Nama:',{defaultValue:d.nama}); if(nama===null)return; const panggilan=await Modal.prompt('Nama Panggilan:',{defaultValue:d.nama_panggilan||''}); if(panggilan===null)return; const kelas=await Modal.prompt('Kelas:',{defaultValue:d.kelas||''}); if(kelas===null)return; const ttl=await Modal.prompt('TTL:',{defaultValue:d.ttl||''}); if(ttl===null)return; const alamat=await Modal.prompt('Alamat:',{defaultValue:d.alamat||''}); if(alamat===null)return; const pin=await Modal.prompt('PIN Baru (kosongkan jika tetap):'); const up={nama,nama_panggilan:panggilan,kelas,ttl,alamat}; if(pin&&pin.trim())up.pin_hash=await SecurityUtil.hashPin(pin.trim()); await db.collection('students').doc(id).update(up); Modal.toast('Tersimpan','Data diupdate.','success'); },
    toggleStd: async function(id,st){ await db.collection('students').doc(id).update({status:st==='off'?'on':'off'}); },
    delStd: async function(id){ const ok=await Modal.confirm('Hapus siswa '+id+'?',{confirmLabel:'Hapus',confirmClass:'danger'}); if(ok)await db.collection('students').doc(id).delete(); },

    // ============ BANK SOAL ============
    bindSoalManagement(){
        document.getElementById('form-add-soal').addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('btn-save-soal');btn.disabled=true; try{ await db.collection('banksoal').add({ pertanyaan:document.getElementById('soal-pertanyaan').value.trim(), opsi:{A:document.getElementById('soal-a').value.trim(),B:document.getElementById('soal-b').value.trim(),C:document.getElementById('soal-c').value.trim(),D:document.getElementById('soal-d').value.trim()}, jawaban_benar:document.getElementById('soal-jawaban').value, pembahasan:document.getElementById('soal-pembahasan').value.trim(), sesi:document.getElementById('soal-sesi').value.trim(), jenis:document.getElementById('soal-jenis').value.trim(), nomor:parseInt(document.getElementById('soal-nomor').value)||0, status:'on', sesi_status:'on', created_at:Date.now() }); document.getElementById('form-add-soal').reset(); Modal.toast('Tersimpan','Soal ditambahkan.','success'); }catch(err){Modal.alert('Gagal: '+err.message,{type:'danger'});}finally{btn.disabled=false;}});
        document.getElementById('form-ai-generate').addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('btn-generate-ai');btn.disabled=true;btn.innerHTML='Berpikir...';document.getElementById('ai-result-area').classList.add('hidden'); const sesi=document.getElementById('ai-sesi').value.trim(); const topic=document.getElementById('ai-topic').value.trim(); const prompt=`Expert English exam creator for Indonesian SMP/MTs (TKA). Create 3 MCQs about ${topic}. ENGLISH questions/options, 4 options A-D, one correct, "pembahasan" in INDONESIAN. Output ONLY JSON array: [{"pertanyaan":"...","opsi":{"A":"...","B":"...","C":"...","D":"..."},"jawaban_benar":"A","pembahasan":"..."}]`; try{ const r=await callGemini(prompt); let t=r.data.candidates[0].content.parts[0].text.replace(/```json\s*/gi,'').replace(/```\s*/g,'').trim(); const a=t.indexOf('['),b=t.lastIndexOf(']'); window.aiResp=JSON.parse(t.substring(a,b+1)); window.aiSesi=sesi; window.aiJenis=topic; document.getElementById('ai-result-container').innerText='✅ '+r.model+'\n'+JSON.stringify(window.aiResp,null,2); document.getElementById('ai-result-area').classList.remove('hidden'); }catch(err){Modal.alert('Gagal: '+err.message,{type:'danger'});}finally{btn.disabled=false;btn.innerHTML='<span class="material-symbols-rounded">smart_toy</span> Generate (AI)';}});
        document.getElementById('btn-discard-ai').addEventListener('click',()=>{document.getElementById('ai-result-area').classList.add('hidden');window.aiResp=null;});
        document.getElementById('btn-save-ai').addEventListener('click',async()=>{ if(!Array.isArray(window.aiResp))return; let nomor=this.nextNomorFor(window.aiSesi); const b=db.batch(); window.aiResp.forEach(s=>{ b.set(db.collection('banksoal').doc(),{pertanyaan:s.pertanyaan,opsi:s.opsi,jawaban_benar:s.jawaban_benar,pembahasan:s.pembahasan||'',sesi:window.aiSesi,jenis:window.aiJenis||'Umum',nomor:nomor++,status:'on',sesi_status:'on',created_at:Date.now()}); }); await b.commit(); document.getElementById('ai-result-area').classList.add('hidden'); window.aiResp=null; Modal.toast('Tersimpan','Soal AI masuk '+window.aiSesi,'success'); });
        document.getElementById('form-import-soal').addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('btn-import-soal');btn.disabled=true; const sesi=document.getElementById('import-sesi').value.trim(); const parsed=this.parseImportText(document.getElementById('import-text').value); try{ if(!parsed.length)throw new Error('Tidak ada soal terdeteksi.'); const ok=await Modal.confirm(parsed.length+' soal → "'+sesi+'"?'); if(ok){ let nomor=this.nextNomorFor(sesi); const b=db.batch(); parsed.forEach(s=>{ b.set(db.collection('banksoal').doc(),{pertanyaan:s.pertanyaan,opsi:s.opsi,jawaban_benar:s.jawaban_benar,pembahasan:s.pembahasan||'',sesi,jenis:s.jenis||'Umum',nomor:s.nomor||nomor++,status:'on',sesi_status:'on',created_at:Date.now()}); }); await b.commit(); document.getElementById('import-text').value=''; Modal.toast('Berhasil',parsed.length+' soal diimport.','success'); } }catch(err){Modal.alert('Gagal: '+err.message,{type:'danger'});}finally{btn.disabled=false;}});
        document.getElementById('review-kategori-filter').addEventListener('change',()=>this.renderReview());
        document.getElementById('soal-jenis-filter').addEventListener('change',()=>this.renderSoalGroups());
    },
    nextNomorFor(sesi){let m=0;this.allSoal.forEach(s=>{if((s.sesi||'Sesi 1')===sesi&&(s.nomor||0)>m)m=s.nomor;});return m+1;},
    parseImportText(text){ const clean=text.replace(/[\u200b\u200c\u200d\ufeff]/g,''); const lower=clean.toLowerCase(); const iJ=lower.indexOf('[jawaban]'),iP=lower.indexOf('[pembahasan]'),iK=lower.indexOf('[kategori]'); let main=clean,ans='',pem='',kat=''; if(iJ!==-1){main=clean.substring(0,iJ);let endA=clean.length;if(iP>iJ)endA=Math.min(endA,iP);if(iK>iJ)endA=Math.min(endA,iK);ans=clean.substring(iJ+9,endA);} else if(iP!==-1){main=clean.substring(0,iP);} if(iP!==-1){let endP=clean.length;if(iK>iP)endP=iK;pem=clean.substring(iP+12,endP);} if(iK!==-1){kat=clean.substring(iK+10);} const qs=[];let cur=null,pend='',pendMax=0; main.split('\n').forEach(line=>{const t=line.trim();if(!t||t.startsWith('['))return; const qm=t.match(/^(\d+)[\.\)]\s*(.*)$/); const om=t.match(/^([a-dA-D])[\.\)]\s*(.*)$/); if(qm){const num=parseInt(qm[1]);let body=qm[2],jenis='';const km=body.match(/\[k:\s*([^\]]+)\]/i);if(km){jenis=km[1].trim();body=body.replace(km[0],'').trim();} let pre=''; if(pend&&num<=pendMax){pre=pend+'\n'; if(num===pendMax)pend='';} else if(pend)pend=''; cur={nomor:num,pertanyaan:pre+body,opsi:{},jenis}; qs.push(cur);} else if(om&&cur){cur.opsi[om[1].toUpperCase()]=om[2];} else{ if(cur&&Object.keys(cur.opsi).length>0){ if(!pend){const hk=/question|soal|untuk|read|text/i.test(t);const nums=hk?(t.match(/\d+/g)||[]).map(Number):[];pendMax=nums.length?Math.max(...nums):cur.nomor+1;} pend+=(pend?'\n':'')+t; } else if(cur){cur.pertanyaan+='\n'+t;} } }); const A={};ans.split('\n').forEach(l=>{const m=l.trim().match(/^(\d+)[\.\)]\s*([a-dA-D])/);if(m)A[+m[1]]=m[2].toUpperCase();}); const P={};let ln=null;pem.split('\n').forEach(l=>{const t=l.trim();if(!t)return;const m=t.match(/^(\d+)[\.\)]\s*(.*)$/);if(m){ln=+m[1];P[ln]=m[2];}else if(ln)P[ln]+='\n'+t;}); const K={};kat.split('\n').forEach(l=>{const t=l.trim();if(!t)return;const m=t.match(/^(\d+)[\.\)]\s*(.*)$/);if(m)K[+m[1]]=m[2];}); return qs.map(q=>({pertanyaan:q.pertanyaan,opsi:q.opsi,jawaban_benar:A[q.nomor]||'A',pembahasan:P[q.nomor]||'',jenis:K[q.nomor]||q.jenis||'Umum',nomor:q.nomor})); },
    bindSoalListener(){ db.collection('banksoal').onSnapshot(snap=>{ this.allSoal=[]; snap.forEach(d=>this.allSoal.push({id:d.id,...d.data()})); this.populateSesiFilter(); this.populateJenisFilter(); this.renderSesi(); this.renderSoalGroups(); this.renderReview(); }); },
    populateSesiFilter(){ const set=[...new Set(this.allSoal.map(s=>s.sesi||'Sesi 1'))].sort(); const sel=document.getElementById('review-kategori-filter'); const cur=sel.value; sel.innerHTML='<option value="">Semua</option>'; set.forEach(k=>sel.innerHTML+=`<option value="${k}">${k}</option>`); sel.value=cur; },
    populateJenisFilter(){ const set=[...new Set(this.allSoal.map(s=>s.jenis||'Umum'))].sort(); const sel=document.getElementById('soal-jenis-filter'); const cur=sel.value; sel.innerHTML='<option value="">Semua Kategori</option>'; set.forEach(k=>sel.innerHTML+=`<option value="${k}">${k}</option>`); sel.value=cur; },
    renderSesi(){ const tbody=document.getElementById('sesi-list-body'); const g={}; this.allSoal.forEach(s=>{const k=s.sesi||'Sesi 1'; if(!g[k])g[k]={c:0,on:0}; g[k].c++; if((s.sesi_status||'on')==='on')g[k].on++;}); tbody.innerHTML=''; const keys=Object.keys(g).sort(); if(!keys.length){tbody.innerHTML='<tr><td colspan="4" class="text-center">Belum ada sesi.</td></tr>';return;} keys.forEach(k=>{const isOn=g[k].on>0; tbody.innerHTML+=`<tr><td><strong>${k}</strong></td><td>${g[k].c} soal</td><td>${isOn?'<span style="color:var(--success);font-weight:bold;">Tampil</span>':'<span style="color:var(--danger);font-weight:bold;">Disembunyikan</span>'}</td><td><label class="switch"><input type="checkbox" class="sesi-toggle" data-sesi="${k}" ${isOn?'checked':''}><span class="slider"></span></label> <button class="btn btn-danger" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.delSesi('${k}')">Hapus</button></td></tr>`;}); tbody.querySelectorAll('.sesi-toggle').forEach(i=>i.addEventListener('change',()=>this.toggleSesi(i.dataset.sesi,i.checked))); },
    toggleSesi: async function(sesi,isOn){ const docs=this.allSoal.filter(s=>(s.sesi||'Sesi 1')===sesi); const b=db.batch(); docs.forEach(s=>b.update(db.collection('banksoal').doc(s.id),{sesi_status:isOn?'on':'off'})); await b.commit(); Modal.toast(isOn?'Sesi Ditampilkan':'Sesi Disembunyikan',sesi,isOn?'success':'warning'); },
    delSesi: async function(sesi){ const ok=await Modal.confirm('Hapus SEMUA soal di '+sesi+'?',{confirmLabel:'Hapus',confirmClass:'danger'}); if(!ok)return; const docs=this.allSoal.filter(s=>(s.sesi||'Sesi 1')===sesi); const b=db.batch(); docs.forEach(s=>b.delete(db.collection('banksoal').doc(s.id))); await b.commit(); },
    renderSoalGroups(){ const c=document.getElementById('soal-group-container'); const f=document.getElementById('soal-jenis-filter').value; const sesiSet=[...new Set(this.allSoal.map(s=>s.sesi||'Sesi 1'))].sort(); const g={}; this.allSoal.forEach(s=>{const k=s.jenis||'Umum'; if(!g[k])g[k]=[]; g[k].push(s);}); let html=''; Object.keys(g).sort().forEach(k=>{ if(f&&k!==f)return; html+=`<h4 style="margin:15px 0 10px;"><span class="badge-jenis">${k}</span> (${g[k].length})</h4>`; g[k].sort((a,b)=>(a.nomor||0)-(b.nomor||0)).forEach(s=>{ const isOn=(s.status||'on')==='on'; const opts=sesiSet.map(x=>`<option value="${x}" ${(s.sesi||'Sesi 1')===x?'selected':''}>${x}</option>`).join(''); html+=`<div class="soal-row"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;"><span class="badge-nomor">No.${s.nomor||'-'}</span><span style="flex:1;font-size:.9rem;">${(s.pertanyaan||'').substring(0,60)}...</span><select class="form-control soal-sesi" data-id="${s.id}" style="width:auto;">${opts}</select><label class="switch"><input type="checkbox" class="soal-toggle" data-id="${s.id}" ${isOn?'checked':''}><span class="slider"></span></label><button class="btn btn-primary" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.editSoal('${s.id}')">Edit</button><button class="btn btn-danger" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.delSoal('${s.id}')">Del</button></div></div>`; }); }); c.innerHTML=html||'<p>Belum ada soal.</p>'; c.querySelectorAll('.soal-toggle').forEach(i=>i.addEventListener('change',()=>this.toggleSoal(i.dataset.id,i.checked))); c.querySelectorAll('.soal-sesi').forEach(sel=>sel.addEventListener('change',()=>this.assignSesi(sel.dataset.id,sel.value))); },
    toggleSoal: async function(id,isOn){ await db.collection('banksoal').doc(id).update({status:isOn?'on':'off'}); },
    assignSesi: async function(id,sesi){ await db.collection('banksoal').doc(id).update({sesi}); Modal.toast('Dipindah','Soal masuk '+sesi,'info'); },
    editSoal: async function(id){ const d=(await db.collection('banksoal').doc(id).get()).data(); if(!d)return; const q=await Modal.prompt('Pertanyaan:',{defaultValue:d.pertanyaan,multiline:true}); if(q===null)return; const jenis=await Modal.prompt('Kategori:',{defaultValue:d.jenis||''}); if(jenis===null)return; await db.collection('banksoal').doc(id).update({pertanyaan:q,jenis}); Modal.toast('Tersimpan','Soal diupdate.','success'); },
    delSoal: async function(id){ const ok=await Modal.confirm('Hapus soal ini?',{confirmLabel:'Hapus',confirmClass:'danger'}); if(ok)await db.collection('banksoal').doc(id).delete(); },

    // MATERI + nav nomor kiri
    renderReview(){ const f=document.getElementById('review-kategori-filter').value; const nav=document.getElementById('materi-qnav'); const c=document.getElementById('review-soal-container'); let list=this.allSoal.slice().sort((a,b)=>(a.sesi||'').localeCompare(b.sesi||'')||(a.nomor||0)-(b.nomor||0)); if(f)list=list.filter(s=>(s.sesi||'Sesi 1')===f); nav.innerHTML=''; let html='';
        list.forEach((s,idx)=>{ html+=`<div class="review-card" id="mat-card-${idx}"><div class="q"><span class="badge-nomor">No.${s.nomor||'-'}</span><span class="badge-kategori">${s.sesi||'Sesi 1'}</span> <span class="badge-jenis">${s.jenis||'Umum'}</span><br>${(s.pertanyaan||'').replace(/\n/g,'<br>')}</div><div class="opts">A. ${s.opsi.A}<br>B. ${s.opsi.B}<br>C. ${s.opsi.C}<br>D. ${s.opsi.D}</div><div class="answer">Kunci: ${s.jawaban_benar}</div><div class="pembahasan"><strong>Pembahasan:</strong><br>${(s.pembahasan||'-').replace(/\n/g,'<br>')}</div></div>`;
            const n=document.createElement('div'); n.className='qn'; n.innerText=idx+1; n.onclick=()=>{const el=document.getElementById('mat-card-'+idx); if(el)el.scrollIntoView({behavior:'smooth',block:'start'});}; nav.appendChild(n); });
        c.innerHTML=html||'<p>Tidak ada soal.</p>'; },

    // ============ REVIEW SISWA AGREGAT (1 soal -> semua siswa) ============
    bindReviewListeners(){ document.getElementById('review-sesi').addEventListener('change',()=>this.renderReviewSiswa()); },
    populateReviewSesi(){ if(!this.resultsSnap)return; const set=[...new Set(this.resultsSnap.docs.map(d=>d.data().kategori||''))].filter(Boolean).sort(); const sel=document.getElementById('review-sesi'); const cur=sel.value; sel.innerHTML='<option value="">Pilih Sesi</option>'; set.forEach(k=>sel.innerHTML+=`<option value="${k}">${k}</option>`); sel.value=cur; },
    renderReviewSiswa(){ const sesi=document.getElementById('review-sesi').value; const nav=document.getElementById('review-qnav'); const box=document.getElementById('review-siswa-container'); if(!sesi||!this.resultsSnap){nav.innerHTML='';box.innerHTML='<p>Pilih sesi.</p>';return;}
        const perStudent={}; this.resultsSnap.forEach(doc=>{ const r=doc.data(); if(r.kategori!==sesi)return; const sid=r.student_id; if(!perStudent[sid]||r.submitted_at>perStudent[sid].submitted_at)perStudent[sid]=r; });
        const results=Object.values(perStudent); if(!results.length){nav.innerHTML='';box.innerHTML='<p>Belum ada hasil di sesi ini.</p>';return;}
        let template=results[0]; results.forEach(r=>{ if((r.questions||[]).length>(template.questions||[]).length)template=r; });
        const qs=template.questions||[]; nav.innerHTML=''; let rows='';
        qs.forEach((q,i)=>{ let chips=''; results.forEach(r=>{ const stu=this.studentMap[r.student_id]||{}; const nama=stu.nama_panggilan||stu.nama||r.student_id; const ua=(r.answers||{})[i]||null; const ok=ua&&ua===q.jawaban_benar; chips+=`<span class="stu-ans ${ok?'ok':'no'}">${nama}: ${ua||'-'}</span>`; });
            const n=document.createElement('div'); n.className='qn'; n.innerText=i+1; n.onclick=()=>{const el=document.getElementById('row-q-'+i); if(el)el.scrollIntoView({behavior:'smooth',block:'center'});}; nav.appendChild(n);
            rows+=`<tr id="row-q-${i}"><td><strong>${i+1}</strong></td><td><strong>${q.jawaban_benar}</strong></td><td>${chips}</td></tr>`; });
        box.innerHTML=`<div class="table-responsive"><table><thead><tr><th>No</th><th>Kunci</th><th>Jawaban Siswa</th></tr></thead><tbody>${rows}</tbody></table></div>`; },

    // ============ OVERVIEW ============
    bindOverviewListeners(){ db.collection('students').onSnapshot(s=>{ this.studentMap={}; s.forEach(d=>{this.studentMap[d.id]=d.data();}); this.renderLive(); }); db.collection('sessions').onSnapshot(s=>{ this.sessionsSnap=s; this.renderLive(); }); db.collection('results').onSnapshot(s=>{ this.resultsSnap=s; this.renderFinal(); this.populateReviewSesi(); this.renderReviewSiswa(); }); },
    renderLive(){ const live=document.getElementById('overview-live-body'); if(!this.sessionsSnap)return; live.innerHTML=''; let has=false; this.sessionsSnap.forEach(doc=>{ const d=doc.data(); if(d&&d.status==='mengerjakan'){ has=true; const stu=this.studentMap[doc.id]||{}; const nama=stu.nama_panggilan||stu.nama||'-'; live.innerHTML+=`<tr><td><strong>${doc.id}</strong> • ${nama}</td><td>${d.sesi||'-'}</td><td style="color:var(--danger);font-weight:bold;">🔴 Mengerjakan</td><td>${d.terjawab}/${d.total_soal}</td><td>${new Date(d.updated_at).toLocaleTimeString()}</td></tr>`; } }); if(!has)live.innerHTML='<tr><td colspan="5" class="text-center">Tidak ada yang ujian.</td></tr>'; },
    renderFinal(){ const fin=document.getElementById('overview-final-body'); if(!this.resultsSnap)return; fin.innerHTML=''; if(this.resultsSnap.empty){fin.innerHTML='<tr><td colspan="8" class="text-center">Belum ada hasil.</td></tr>';return;} this.resultsSnap.forEach(doc=>{ const r=doc.data(); const stu=this.studentMap[r.student_id]||{}; const nama=stu.nama_panggilan||stu.nama||'-'; fin.innerHTML+=`<tr><td><strong>${r.student_id}</strong> • ${nama}</td><td>${r.kategori||'-'}</td><td style="color:var(--primary);font-weight:bold;">${r.score}</td><td style="color:var(--success);">${r.correct}</td><td style="color:var(--danger);">${r.incorrect}</td><td>${r.unanswered}</td><td>${new Date(r.submitted_at).toLocaleString()}</td><td><button class="btn btn-danger" style="padding:4px 8px;font-size:.75rem;width:auto;" onclick="AdminApp.delResult('${doc.id}')">Hapus</button></td></tr>`; }); },
    delResult: async function(id){ const ok=await Modal.confirm('Hapus hasil ini?',{confirmLabel:'Hapus',confirmClass:'danger'}); if(ok)await db.collection('results').doc(id).delete(); }
};
document.addEventListener('DOMContentLoaded',()=>AdminApp.init());